Update to Proxmox 9 (#18)
* Use deb822 format

* By default seems there is no /etc/sysctl.conf so you will get this
error: sysctl: cannot open "/etc/sysctl.conf": No such file or directory